add mocks generation + add worker mocks
cadence-workflow/cadence-go-client pull request #1239
Opened 2023-03-24 01:10 UTC by sapk

This PR add mock generation with latest version and add worker.Registry and worker.Worker mocks.

I want to be able to unit test registration of my worker so I need at least the registry mock. If I generate on my side it link to internal package which is forbidden. I can remediate this limitation on my side with writing a custom mock but I feel it maybe useful to other to have a clean generate one in this repository along side the others provided mocks.

I validated that I can use this in my repository by using a replace in the go.mod since we can link to internal in the same repository.

Risk should be low as it only update or add new mocks.

Some part of this PR are probably opinionated (ex go:generate comments) so let me know if it need any change.

2023-03-24 01:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber-go/cadence-client?pullRequest=1239) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber-go/cadence-client?pullRequest=1239) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber-go/cadence-client?pullRequest=1239) it.</sub>

2023-03-28 21:24 UTC, Groxx commented
tbh I'm planning on deleting these mocks entirely in a future version.  mocks can be generated client-side in the library of their choice, rather than being stuck with our code / tool versions / etc.

I haven't dug into them super closely, but AFAICT they aren't relying on any `internal/` visibility rules, so they should be fully possible to build externally.  or are there in fact problems with that?

2023-03-28 22:07 UTC, sapk commented
Yes the main reason for the need for internal is that mockery translate the aliased options struct to internal ones. Like in the generated one (ex:worker) in this MR.

It can be work around by doing a manual version of the mock to not rely on the aliased internal options.

Maybe the real solution is to fix mockery to not uncover the alias 😅.

Otherwise, I totally understand if you want to remove them. It was just to ease if someone else had the same need.

2023-03-28 23:25 UTC, Groxx commented
Yeah, we've been having that issue with mockery and gomock internally too.

Gomock at least has a "source" mode in the flags (as opposed to using reflection), which seems to work better.

Otherwise, I'm hoping that we'll have a v2 of this client library soon (a literal v2, so you can use both and migrate gradually), and that'll definitely be getting rid of those internal aliases.  There's just no way to do so without making other breaking changes, so it has to wait for v2.

2023-03-28 23:52 UTC, Groxx commented
but in the meantime!  if you're interested, I think this could work.  I want to pin versions though, and bake them into the makefile - it's not too hard.

do you want to attempt that, or should I just prep a commit/? for you?  I'm not entirely sure how to do that within github, but it's easy enough to just prep something to copy/paste.

2023-03-29 00:51 UTC, Groxx commented
eh, that took more fiddling than expected.
https://github.com/Groxx/cadence-client/commit/921c783fd82e69fc3c04e7b6f9a59182115ae40b <- if you want to add those changes, we can merge this :)

2026-08-28 16:06 UTC, zawadzkidiana reviewed
Thanks for this, @sapk — and sorry it's been over three years without a resolution. `worker.Registry`/`worker.Worker` mocks fill a real gap: anyone testing their own worker setup without `internal/` visibility currently has to hand-roll these, so having maintained ones alongside the existing `client.Client`/`client.DomainClient` mocks is genuinely useful.

Things that stand out as solid:
- The regen is a clean mockery v1.0.0 → v2.23.0 upgrade with no manual hand-edits mixed in — `Client.go`, `DomainClient.go`, `HistoryEventIterator.go`, `Value.go`, `WorkflowRun.go` all pick up the same generator-driven changes (constructor helpers, the `r0, r1` two-return-value shortcut, import grouping).
- `mocks/verify.go` gets `//go:generate` directives plus compile-time interface assertions for every mock, including the two new ones — good hygiene, and it documents exactly how to reproduce each file.
- Nice catch, possibly unintentional but worth calling out: `DomainClient.Update`'s existing mock was calling `_m.Called(ctx)`, silently dropping `request` from the mock's argument matching. The regen fixes that to `_m.Called(ctx, request)`, which is a real correctness fix riding along with this PR.

The blocking issue is that this stalled mid-conversation rather than being rejected. Back in 2023, @Groxx raised a fair concern (mocks might get deleted entirely in a future major version so users can generate their own) but then proposed a concrete way forward — pinning mockery's version in the Makefile — and pushed a sample commit (`Groxx/cadence-client@ff949d2`) for you to pull in. That commit never made it into this branch, and the PR now shows merge conflicts against current `master`, so it can't be evaluated as-is.

Given the age: are you still interested in carrying this forward? If so, rebasing onto `master` and folding in Groxx's Makefile-pinning suggestion would resolve the one open concern and give this a real shot at merging. If not, a maintainer could pick up just the `worker.Registry`/`worker.Worker` mocks (the part with clear consensus) referencing this PR. Either way, thanks for the contribution and the patience.

Minor nit for whenever this is revisited: `mocks/.mockery.yaml` is missing a trailing newline.

---
_Generated by [Claude Code](https://claude.ai/code)_

2026-09-01 16:05 UTC, zawadzkidiana reviewed
Thanks for this, @sapk — sorry it's been sitting since the good back-and-forth with @Groxx in March 2023 wound down without a conclusion.

On the change itself, this is more than a "regenerate with a newer mockery" diff — a few things stand out:

1. **A genuine bugfix is bundled in here**: `DomainClient.Update`'s mock previously called `_m.Called(ctx)`, silently dropping the `request` argument, so any `.On("Update", ctx, req)` expectation set on that mock could never actually match on `request`. This PR fixes it to `_m.Called(ctx, request)` — a real correctness fix for existing test doubles, separate from the new mocks. Worth calling out explicitly in the description since it's easy to miss inside a "just regenerating mocks" diff.
2. **New `Registry`/`Worker` mocks**: as discussed in the thread, these mock the public `worker.Registry`/`worker.Worker` interfaces rather than reaching into `internal/`, so they're buildable outside this module — a reasonable addition for anyone unit-testing worker registration.
3. The generated-code housekeeping (mockery v2.23.0, `NewXxx(t)` constructors, `//go:generate` directives added to `verify.go`, copyright year bump) reads as standard, low-risk mockery-version churn.

Given @Groxx's comment about eventually deleting these mocks entirely in a v2 client, is that still the plan? If so, worth confirming whether this is still wanted before asking for the (now more involved, since `master` has moved on since 2023) rebase — the branch is showing conflicts against current `master`. If the mocks are staying for now, the `DomainClient.Update` fix in particular seems worth not losing to bit-rot.

---
_Generated by [Claude Code](https://claude.ai/code)_

2026-09-03 23:01 UTC, zawadzkidiana requested changes
Closing because important bits were merged.

2026-09-03 23:02 UTC, closed without merging